#springcloud中Eureka注册中心的端口号
server:
  port: 10086
#服务的名称
spring:
  application:
    name: eureka
eureka:
  client:
    fetch-registry: false #true的时候Eureka client在启动时会从Eureka server获取注册信息并缓存到本地，之后只会增量获取信息 false则是每次全量获取
    register-with-eureka: false #是否开启相互注册
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/ #eureka的url
  instance:
    prefer-ip-address: true